services:
  labelstudio:
    image: heartexlabs/label-studio:latest
    volumes:
      - ./data:/label-studio/data
      - ./files:/label-studio/files
      - /home/filip/gabinet/data:/label-studio/files/gabinet
    environment:
      - CSRF_TRUSTED_ORIGINS=https://labelstudio.krzyzanowski.dev
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK=true
